LUA ?= luajit
LUA_LIBDIR = -LC:/LuaJIT/lib
LUA_INCDIR = -IC:/LuaJIT/include
CC = gcc

LIBFLAG = -shared -llua51
CFLAGS = -O2 -Wall -Werror

.PHONY: all clean install

all: lua_system_constants.dll

lua_system_constants.dll: lua_system_constants.o
	$(CC) $(LIBFLAG) $(LUA_LIBDIR) -o $@ $<
	$(LUA) test/lua_system_constants_test.lua

%.o: %.c
	$(CC) -c $(CFLAGS) $(LUA_INCDIR) $< -o $@

install: lua_system_constants.dll
	cp lua_system_constants.dll $(INST_LIBDIR)

clean:
	rm -f *.dll *.o *.rock
